### ISSUE TITLE
You misspelled Haskell

### ISSUE THREAD

**Issue by ggVGc** [AshyIsMe/hircules#1]
"Haskel irc bot". Good job.

**Comment by AshyIsMe** [comment]
Sweet, gmail buried the notification for this so I actually never saw it in my inbox

**Comment by jotham** [comment]
> @ggVGc YOUR PROFILE PIC DOESN'T SEEM APPROPRIATE

**Comment by ggVGc** [comment]
Closing as description has been updated, and also the author has abandoned our community.
